name: Release Library

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create the PCM package
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Release tag $VERSION"
          python3 package.py $VERSION
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/package.zip
          asset_name: package.zip
          asset_content_type: application/zip
      - name: Commit and Push Changes to Main Branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'update metadata.json'
          branch: main
