name: Release Library

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create the PCM package
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Release tag $VERSION"
          python package.py $VERSION
      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
          setup-java: false
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push Changes to Main Branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'update json files'
          branch: main
